---

version: 1

projects:
    - proj1
    - proj2

libs:
    - lib1
    - lib2
    - libnnn

pcb:
    dim: [20000, 20000]
    colors:
        back: [0, 0, 0]
        grid1: [64, 64, 64]
        grid2: [222, 222, 222]
        guide: [255, 255, 255]
        layer:
            tpaste:
            tglue:
            tsilk:
            tmask:
            top: [255, 128, 128, 127]
            l1:
            l2:
            l3:
            l4:
            l5:
            l6:
            bottom: [128, 128, 255, 127]
            bmask:
            bsilk:
            bglue:
            bpaste:
            edge:
            keepout:
            aux1:
            aux2:
            aux3:
            aux4:
            aux5:
    shortcuts:
        grid: G
        place:
            - P
            - text: S
              pad: P
              via: V
              line: L
              arc: R
              area: A
        trace: T
        delete: Del
        clearsel: X
        setorigin: O
        resetorigin: R
        rotate: Space
        layer: L

sch:
    dim: [20000, 20000]
    colors:
        back: [245, 239, 191]
        grid1: [80, 80, 208]
        grid2: [222, 30, 60]
        guide: [0, 0, 110]
        item:
            wire:
            junction:
            bus:
            busnentry:
            pin:
            text:
            net:
            port:
            art:
    shortcuts:
        grid: G
        place:
            - P
            - part: P
              power: O
              text: S
              line: L
              arc: R
        trace: T
        junction: J
        delete: DEL
        clearsel: X
        setorigin: O
        resetorigin: R
        rotate: Space
...
